version: '3.8'

services:
  motortown:
    build: .
    container_name: motortown-server
    env_file:
      - .env
    volumes:
      - ./server:/motortown/server
      - ./config:/motortown/config
      - ./backup:/motortown/backup
    ports:
      - "${PORT_1}:${PORT_1}/udp"
      - "${PORT_2}:${PORT_2}/udp"
    restart: unless-stopped
