version: '3.8'

services:
  motortown:
    build: .
    container_name: motortown-server
    volumes:
      - ./server:/motortown/server
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped
