version: '3.8'

services:
  motor-town-server:
    build: .
    container_name: motor-town-server
    ports:
      - "${PORT_1:-27015}:${PORT_1:-27015}/udp"
      - "${PORT_2:-27016}:${PORT_2:-27016}/udp"
    environment:
      STEAM_USERNAME: "${STEAM_USERNAME:-your_steam_username}"
      STEAM_PASSWORD: "${STEAM_PASSWORD:-your_steam_password}"
      EXE_NAME: "${EXE_NAME:-MotorTownServer-Win64-Shipping.exe}"
      MAP_NAME: "${MAP_NAME:-Jeju_World}"
      PORT_1: "${PORT_1:-27015}"
      PORT_2: "${PORT_2:-27016}"
      USE_PERF_THREADS: "${USE_PERF_THREADS:-true}"
      ENABLE_LOG: "${ENABLE_LOG:-true}"
      HEADLESS: "${HEADLESS:-false}"
    volumes:
      - ./server:/mnt/server
    entrypoint: ["/mnt/server/entrypoint.sh"]
